/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { Beer, Equipment } from "./types";

export const BEERS: Beer[] = [
  {
    id: "pilsen",
    name: "Pilsen",
    style: "Cerveja clara e leve",
    description: "Nossa Pilsen é uma cerveja clara, leve e extremamente refrescante. Ideal para todos os tipos de celebrações.",
    abv: "4.8%",
    ibu: 12,
    price30L: 450,
    price50L: 750,
    tag: "A MAIS PEDIDA",
    badge: "R$ 15,00/L",
    image: "https://images.unsplash.com/photo-1618885472118-20cff466bc11?auto=format&fit=crop&q=80&w=800",
  },
  {
    id: "american-ipa",
    name: "American IPA",
    style: "Lúpulos Americanos",
    description: "Cerveja com lúpulos americanos selecionados, trazendo aroma cítrico e amargor equilibrado.",
    abv: "6.2%",
    ibu: 45,
    price30L: 660,
    price50L: 1100,
    tag: "PARA AMANTES DE LÚPULO",
    badge: "R$ 22,00/L",
    image: "https://images.unsplash.com/photo-1535958636474-b021ee887b13?auto=format&fit=crop&q=80&w=800",
  },
  {
    id: "cream-ale",
    name: "Cream Ale",
    style: "Com limão siciliano",
    description: "Refrescante e leve, com a adição de limão siciliano. Abv 4,8% Ibu 12.",
    abv: "4.8%",
    ibu: 12,
    price30L: 540,
    price50L: 900,
    tag: "TOQUE CÍTRICO",
    badge: "R$ 18,00/L",
    image: "https://images.unsplash.com/photo-1514933651103-005eec06c04b?auto=format&fit=crop&q=80&w=800",
  },
  {
    id: "weiss",
    name: "WEISS",
    style: "Cerveja com malte de trigo",
    description: "Cerveja de trigo tradicional, com notas características de cravo e banana.",
    abv: "5.0%",
    ibu: 12,
    price30L: 540,
    price50L: 900,
    tag: "TRADICIONAL",
    badge: "R$ 18,00/L",
    image: "https://images.unsplash.com/photo-1571705042748-55fdee1ea47b?auto=format&fit=crop&q=80&w=800",
  },
  {
    id: "red-ale",
    name: "Chope Red Ale",
    style: "Maltes levemente tostados",
    description: "Cerveja avermelhada com complexidade de maltes levemente tostados.",
    abv: "5.4%",
    ibu: 18,
    price30L: 540,
    price50L: 900,
    tag: "MALTE TOSTADO",
    badge: "R$ 18,00/L",
    image: "https://images.unsplash.com/photo-1559526323-cb2f2fe2591b?auto=format&fit=crop&q=80&w=800",
  },
  {
    id: "morango",
    name: "Chope de Morango",
    style: "Frutada & Doce",
    description: "Chopp frutado com sabor intenso de morango, perfeito para quem busca doçura e frescor.",
    abv: "4.5%",
    ibu: 8,
    price30L: 540,
    price50L: 900,
    tag: "FRUTADA",
    badge: "R$ 18,00/L",
    image: "https://images.unsplash.com/photo-1597075095400-0e122f5f4581?auto=format&fit=crop&q=80&w=800",
  },
];

export const EQUIPMENTS: Equipment[] = [
  {
    id: "naja",
    name: "Torre Naja 2 Vias Congelada",
    category: "LINHA PRIME / EVENTOS VIP",
    description: "Visual icônico com congelamento externo na torre. Serve 2 tipos de chopp simultâneos sem perda de temperatura, mesmo sob sol intenso.",
    capacity: "70 Litros / Hora",
    power: "220V Monofásico",
    taps: "2 Torneiras Italianas com Compensador",
    idealFor: "Ideal para Casamentos e Formaturas",
    image: "https://images.unsplash.com/photo-1514933651103-005eec06c04b?auto=format&fit=crop&q=80&w=800",
    specs: [
      { label: "Vazão Contínua", value: "70 Litros / Hora" },
      { label: "Controle Térmico", value: "Digital (-1.5°C a +2°C)" },
      { label: "Alimentação", value: "220V Monofásico" },
      { label: "Torneiras", value: "2 Torneiras Italianas" },
    ],
  },
  {
    id: "eletrica",
    name: "Elétrica Bancada Portátil",
    category: "VERSÁTIL / PRÁTICA",
    description: "Compacta e silenciosa. Ocupa pouco espaço na bancada gourmet, quiosque ou salão de festas. Disponível com 1 ou 2 vias de extração rápida.",
    capacity: "45 a 55 L / Hora",
    power: "220V ou 110V",
    taps: "1 ou 2 Torneiras Italianas",
    idealFor: "Ideal para Aniversários & Churrascos",
    image: "https://images.unsplash.com/photo-1584225065152-4a1454aa3d4e?auto=format&fit=crop&q=80&w=800",
    specs: [
      { label: "Vazão Contínua", value: "45 a 55 L / Hora" },
      { label: "Tempo p/ Gelar", value: "5 a 10 Minutos" },
      { label: "Alimentação", value: "220V ou 110V" },
      { label: "Torneiras", value: "1 ou 2 Torneiras Italianas" },
    ],
  },
  {
    id: "gelo",
    name: "Choppeira a Gelo Premium",
    category: "100% AUTÔNOMA",
    description: "Isolamento térmico robusto em poliuretano injetado com serpentina em inox de 32 metros. Funciona perfeitamente onde não há tomada elétrica.",
    capacity: "Até 12 Horas de Gelo",
    power: "Dispensa Tomada",
    taps: "1 Torneira Italiana Inox",
    idealFor: "Ideal para Sítios, Ranchos & Áreas Externas",
    image: "https://images.unsplash.com/photo-1582234372722-50d7ccc30ebd?auto=format&fit=crop&q=80&w=800",
    specs: [
      { label: "Capacidade Térmica", value: "Até 12 Horas de Gelo" },
      { label: "Eletricidade", value: "NENHUMA" },
      { label: "Carga de Gelo", value: "15 a 20 kg" },
      { label: "Torneiras", value: "1 Torneira Italiana Inox" },
    ],
  },
];
